apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
data:
  JWT_KEY: WU9VUl9TVVBFUlNFQ1JFVA== #base64 -cmd:  echo -n 'YOUR_SUPERSECRET' | base64
  #kubectl create secret generic jwt-secret --from-literal=JWT_KEY=YOUR_SUPERSECRET
