apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
data:
  JWT_KEY: eW91cl9qd3Rfa2V5
  GOOGLE_PROJECT_ID: eW91cl9wcm9qZWN0X2lk
  GOOGLE_STORAGE_BUCKET_NAME: eW91cl9nb29nbGVfc3RvcmFnZV9idWNrZXRfbmFtZQ==
  GOOGLE_CLIENT_ID: eW91cl9nb29nbGVfY2xpZW50X2lk
  GOOGLE_CLIENT_SECRET: eW91cl9nb29nbGVfY2xpZW50X3NlY3JldA==
  SENDGRID_API_KEY: eW91cl9zZW5kZ3JpZF9hcGlfa2V5
  SENDGRID_SENDER_EMAIL: eW91cl9zZW5kZ3JpZF9zZW5kZXJfZW1haWw=

  #JWT_KEY cmd:  echo -n 'your_jwt_key' | base64
  #GOOGLE_PROJECT_ID cmd:  echo -n 'your_project_id' | base64
  #GOOGLE_STORAGE_BUCKET_NAME cmd:  echo -n 'your_google_storage_bucket_name' | base64
  #GOOGLE_CLIENT_ID cmd:  echo -n 'your_google_client_id' | base64
  #GOOGLE_CLIENT_SECRET cmd:  echo -n 'your_google_client_secret' | base64
  #SENDGRID_API_KEY cmd:  echo -n 'your_sendgrid_api_key' | base64
  #SENDGRID_SENDER_EMAIL cmd:  echo -n 'your_sendgrid_sender_email' | base64

  #kubectl create secret generic jwt-secret --from-literal=JWT_KEY=YOUR_SUPERSECRET

  #Don't forget to create the google-application-credentials secret with in the folder where the JSON is
  #kubectl create secret generic google-application-credentials --from-file=google-application-credentials.json=./google-application-credentials.json
